image_norm_mean: [0.485, 0.456, 0.406] # ${.train_transform._args_[5].mean}
image_norm_std: [0.229, 0.224, 0.225] #${.train_transform._args_[5].std}

normalize_transform:
  - _target_: tr_learn.data.transforms.convert_dtype
  - _target_: torchvision.transforms.Normalize
    _convert_: "partial"
    mean: ${...image_norm_mean}
    std: ${...image_norm_std}

resize_crop_transform:
  _target_: torchvision.transforms.v2.RandomResizedCrop
  _convert_: "partial"
  size: [224]
  interpolation:
    _target_: tr_learn.data.transforms.to_interpolation_mode
    mode: "BILINEAR"
  scale:
    _target_: tr_learn.data.transforms.to_tuple
    items: [0.5, 1.0]
  ratio:
    _target_: tr_learn.data.transforms.to_tuple
    items: [0.9, 1.2]
  antialias: true

augment_transforms:
  - _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
        p: 1.0
      - ${....resize_crop_transform}
      - ${....normalize_transform[0]}
      - ${....normalize_transform[1]}

  - _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.RandomVerticalFlip
        p: 1.0
      - ${....resize_crop_transform}
      - ${....normalize_transform[0]}
      - ${....normalize_transform[1]}

  - _target_: torch.nn.Sequential
    _args_:
      - ${....resize_crop_transform}
      - _target_: torchvision.transforms.v2.ColorJitter
        hue: 0.5
        saturation: 0.25
        contrast: 0.5
        brightness: 0.5
      - ${....normalize_transform[0]}
      - ${....normalize_transform[1]}
    
  - _target_: torch.nn.Sequential
    _args_:
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
        p: 0.6
      - _target_: torchvision.transforms.v2.RandomVerticalFlip
        p: 0.6
      - ${....resize_crop_transform}
      - _target_: torchvision.transforms.v2.ColorJitter
        hue: 0.5
        saturation: 0.25
        contrast: 0.5
        brightness: 0.5
      - ${....normalize_transform[0]}
      - ${....normalize_transform[1]}

train_transform: ${.augment_transforms}

valid_transform: ${.augment_transforms}

test_transform:
  - _target_: torch.nn.Sequential
    _args_:
        - _target_: torchvision.transforms.Resize
          interpolation:
            _target_: tr_learn.data.transforms.to_interpolation_mode
            mode: "BILINEAR"
          _convert_: "partial"
          antialias: true
          size: [224]
        - _target_: torchvision.transforms.CenterCrop
          size: 224
        - ${....normalize_transform[0]}
        - ${....normalize_transform[1]}

