image_norm_mean: [0.485, 0.456, 0.406] # ${.train_transform._args_[5].mean}
image_norm_std: [0.229, 0.224, 0.225] #${.train_transform._args_[5].std}

train_transform:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torchvision.transforms.Resize
      _convert_: 'partial'
      antialias: true
      size: [224]
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: tr_learn.data.transforms.convert_dtype
    - _target_: torchvision.transforms.Normalize
      _convert_: 'partial'
      mean: ${....image_norm_mean}
      std: ${....image_norm_std}

valid_transform:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torchvision.transforms.Resize
      _convert_: 'partial'
      antialias: true
      size: [224]
    - _target_: torchvision.transforms.CenterCrop
      size: 224
    - _target_: tr_learn.data.transforms.convert_dtype
    - _target_: torchvision.transforms.Normalize
      _convert_: 'partial'
      mean: ${....image_norm_mean}
      std: ${....image_norm_std}
