_target_: tr_learn.data.datamodule.PlateDataModuleTrain
train_load_info:
  _target_: tr_learn.data.datamodule.LoadInfo
  root: ./data/raw/plates
  batch_size: ???
  transform: ???
predict_load_info:
  _target_: tr_learn.data.datamodule.LoadInfo
  root: ${..train_load_info.root}
  is_jit_transform: ${..train_load_info.is_jit_transform}
  batch_size: 8
  num_workers: 4
  transform: ???