_target_: tr_learn.data.datamodule.PlateDataModuleTrainValid
train_load_info:
  _target_: tr_learn.data.datamodule.LoadInfo
  is_jit_transform: true
  root: ./data/raw/plates
  batch_size: ???
  transforms: ???
  num_workers: 0
valid_load_info:
  _target_: tr_learn.data.datamodule.LoadInfo
  root: ${..train_load_info.root}
  is_jit_transform: ${..train_load_info.is_jit_transform}
  batch_size: ???
  transforms: ???
  num_workers: 0
predict_load_info:
  _target_: tr_learn.data.datamodule.LoadInfo
  root: ${..train_load_info.root}
  is_jit_transform: ${..train_load_info.is_jit_transform}
  batch_size: 8
  transforms: ???
  num_workers: 4
